test *args:
	deno test --allow-env --env=.env.test --unstable-kv {{args}}

deploy * args:
	deployctl deploy --prod --import-map=import_map.json {{args}}

docker-build:
	docker build -t umajho/bangumi-episode-ratings .

docker-push:
	docker image push umajho/bangumi-episode-ratings:latest