test *args:
	deno test --allow-env --env=.env.test --unstable-kv {{args}}

test-cov:
	deno test --allow-env --env=.env.test --unstable-kv --coverage=coverage
	deno coverage ./coverage --lcov > coverage.lcov

deploy * args:
	deployctl deploy --prod --import-map=import_map.json {{args}}

docker-build:
	docker buildx build --platform=linux/amd64 \
		-t umajho/bangumi-episode-ratings:latest \
		-t umajho/bangumi-episode-ratings:$(cat deno.json | jq -r .version) \
		.

docker-build-tmp:
	docker build -t umajho/bangumi-episode-ratings:tmp .

docker-push-latest:
	docker image push umajho/bangumi-episode-ratings:$(cat deno.json | jq -r .version)
	docker image push umajho/bangumi-episode-ratings:latest
