test *args:
	deno test --allow-env --env=.env.test --unstable-kv {{args}}

deploy * args:
	deployctl deploy --prod --import-map=import_map.json {{args}}

docker-build:
	docker build \
		-t umajho/bangumi-episode-ratings:latest \
		-t umajho/bangumi-episode-ratings:$(cat deno.json | jq -r .version) \
		.

docker-build-tmp:
	docker build -t umajho/bangumi-episode-ratings:tmp .

docker-push:
	docker image push --all-tags umajho/bangumi-episode-ratings
